#!/bin/bash

set -e

tag=$(./devstep -v)

echo "===> Building fgrehm/devstep:${tag}"
docker build -t fgrehm/devstep:${tag} .

echo "===> Building fgrehm/devstep-sa:${tag}"
(cd standalone && docker build -t fgrehm/devstep-sa:${tag} .)

echo "===> Building fgrehm/devstep-ab:${tag}"
(cd auto-build && docker build -t fgrehm/devstep-ab:${tag} .)
