#!/bin/bash

set -e

tag='v0.3.1'

echo "===> Building fgrehm/devstep:${tag}"
docker build -t fgrehm/devstep:${tag} .

echo "===> Building fgrehm/devstep-ab:${tag}"
(cd auto-build && docker build -t fgrehm/devstep-ab:${tag} .)
