#!/bin/bash

SQUID_SHARED="${HOME}/devstep/plugins/squid3/shared"

if ! $(docker ps -a | grep -q squid3); then
  echo 'Creating squid container'
  docker run -ti -P -d \
        -h squid3.dev\
        -v $SQUID_SHARED/cache:/var/cache/squid3 \
        -v $SQUID_SHARED/certs:/etc/squid3/certs \
        --name squid3 \
        fgrehm/squid3-ssl:v20140809
else
  if ! $(docker ps | grep -q squid3); then
    echo 'Restarting squid container'
    sudo mkdir -p $SQUID_SHARED/{certs,cache}
    docker start squid3 &> /dev/null
  else
    echo 'Squid container is already running'
  fi
fi
